
CREATE TABLE IF NOT EXISTS users (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    login varchar(100) NOT NULL,
    birthday timestamp,
    email varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS friendship (
    friendship_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id long REFERENCES users (id),
    friend_id long REFERENCES users (id),
    status varchar(50)
    );

CREATE TABLE IF NOT EXISTS rating (
    rating_id INTEGER PRIMARY KEY,
     rating_name varchar(20) NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
    id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name varchar(100) NOT NULL,
    description varchar(200),
    release_date timestamp,
    duration int,
    rating int REFERENCES rating (rating_id)
    );

CREATE TABLE IF NOT EXISTS genres (
     genre_id INTEGER PRIMARY KEY,
    genre_name varchar(100) NOT NULL
    );

CREATE TABLE IF NOT EXISTS film_genres (
    film_genres_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id long REFERENCES films (id),
    genre_id int REFERENCES genres (genre_id)
    );

CREATE TABLE IF NOT EXISTS likes (
    likes_id long GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id long REFERENCES films (id),
    user_id long REFERENCES users (id)
    );